### ISSUE TITLE
Modification d'info ESDAC

### ISSUE THREAD

**Issue by Natouille** [sudweb/2017#31]
L'entrée se fera non pas boulevard de la République mais via l'impasse.

> "L'entrée au site se fait sur le passage Thibaud, à gauche après le 11 boulevard de la République"

**Comment by borisschapira** [comment]
Hum, après, avant, tout dépend d'où on arrive.

**Comment by borisschapira** [comment]
Je vais mettre "L'entrée au site se fait sur le passage Thibaud, entre le 13 et le 19, boulevard de la République." Ça prête moins à confusion, je pense.
