### ISSUE TITLE
Erreur de lien Twitter sur orateur

### ISSUE THREAD

**Issue by Natouille** [sudweb/2017#37]
### Comportement constaté

Sur la page programme, le lien sur Sylvain Achard et Étienne Voilliot est KO
https://twitter.com/https://twitter.com/cutesquirrel

### Comportement attendu
https://twitter.com/cutesquirrel

@sudweb/thym

**Comment by DirtyF** [comment]
corrigé dans https://github.com/sudweb/2017/commit/3456918e6f0ffa3ea44648524671ea6cb80e74a3
