### ISSUE TITLE
Ballader > balader

### ISSUE THREAD

**Issue by Natouille** [sudweb/2017#40]
### Comportement constaté

Sur la page des moments de détente, le dimanche c'est écrit "vous ballader"

### Comportement attendu
balader (quand on se promène, sinon c'est la ballade qu'on chante)

### Étapes pour reproduire le problème

-
- 
- 

@sudweb/thym

**Comment by DirtyF** [comment]
Sud Web c'est la ballade des gens heureux, c'est pour ça :)
