### ISSUE TITLE
Encrypter les emails des participants en MD5 via le script de récupération

### ISSUE THREAD

**Issue by borisschapira** [sudweb/2017#41]
### Comportement constaté

Lorsqu'on exécute le script de récupération des inscrits Weezevent, on récupère les emails des participants qui, si on n'y prête pas attention, peuvent se retrouver publiés dans le code source, librement accessibles.

### Comportement attendu

 Durant la transformation de ces données en données utilisables pour réaliser le rendu de la page "Participant·e·s", il faudrait obfusquer les emails via un hashage MD5.

### Étapes pour reproduire le problème

- Se munir des identifiants et API Key Weezevent
- Utiliser l'API Weezevent pour récupérer un Access Token
- Utiliser cet Access Token pour récupérer la liste des participants via `script/gen-attendees`
- Constater la présence des emails non-hashé dans `_data/attendees.json`

### Piste de résolution

* À court terme, réencoder les emails en MD5 avant de pousser le code sur Github.
* À moyen terme, surveiller l'arrivée de méthodes de hashage intégrées à `jq` : https://github.com/stedolan/jq/issues/1116

@sudweb/thym

**Comment by DirtyF** [comment]
le fichier `_data/attendees.json` est maintenant généré pendant le build sur Travis et n'est plus versionné dans le dépôt. Les seuls mails visibles dans le source sont ceux des personnes qui n'ont pas renseigné ou de compte Twitter.
