### ISSUE TITLE
Les images des profils Twitter des participants ne s'affichent plus

### ISSUE THREAD

**Issue by antoinentl** [sudweb/2017#42]
### Comportement constaté
Les images des profils Twitter des participants ne s'affichent plus, sur la page [Participants](https://sudweb.fr/2017/participants/).

### Comportement attendu
Que les images s'affichent.

### Étapes pour reproduire le problème
Se rendre sur la page [Participants](https://sudweb.fr/2017/participants/) avec Firefox (sous Android ou Ubuntu) ou Chrome (sous Android) comme navigateur.

### Piste pour résoudre le problème
<strike>Modifier le schéma des URLs des images des profils Twitter des participants :

- actuellement : `https://twitter.com/{name_user}/profile_image?size=bigger`
- désormais : `https://pbs.twimg.com/profile_images/{id_user}/{id_image}_bigger.jpg`</strike>

C'est un problème qui a pour origine le [blocage](https://developer.mozilla.org/fr/Firefox/Privacy/protection_contre_le_pistage) d'une ressource extérieure, une idée pour résoudre cela ?

@sudweb/thym

**Comment by antoinentl** [comment]
Complément pour reproduire le bug : Firefox + navigation privée (pas de compte Twitter connecté).

+ @DirtyF

**Comment by DirtyF** [comment]
Merci @antoinentl, je reproduis bien aussi sur Chrome / Androïd.
